version: '4.2'

services:
  postgres:
    image: postgres:15-alpine
    container_name: book_reservation
    env_file:
      - .env
    volumes:
      - book_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    book_pg_data:
